/*
 * Bitcoin API
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.astarlabs.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SingleResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-03-15T19:24:21.978-03:00")
public class SingleResult {
  @SerializedName("result")
  private String result = null;

  @SerializedName("error")
  private Boolean error = null;

  public SingleResult result(String result) {
    this.result = result;
    return this;
  }

   /**
   * result
   * @return result
  **/
  @ApiModelProperty(example = "null", value = "result")
  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public SingleResult error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * true or false
   * @return error
  **/
  @ApiModelProperty(example = "null", value = "true or false")
  public Boolean getError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SingleResult singleResult = (SingleResult) o;
    return Objects.equals(this.result, singleResult.result) &&
        Objects.equals(this.error, singleResult.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(result, error);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SingleResult {\n");
    
    sb.append("    result: ").append(toIndentedString(result)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

