/*
 * Bitcoin API
 * Blockchain Facilities
 *
 * OpenAPI spec version: 2.0.0
 * Contact: contato@astarlabs.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package br.com.astarlabs.client.api;

import java.util.List;

import org.junit.Ignore;
import org.junit.Test;

import br.com.astarlabs.client.ApiException;
import br.com.astarlabs.client.Token;
import br.com.astarlabs.client.model.Transaction;

/**
 * API tests for SearchApi
 */

public class SearchApiTest {

    private final SearchApi api = new SearchApi();
    
    /**
     * Get transaction informations by API ID
     *
     * Get transaction informations by API ID 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore
    @Test
    public void searchByAPIIDTest() throws ApiException {
    	
        String token = null;
		try {
			token = Token.sign("YOUR API PRIVATE KEY");
		} catch (Exception e) {
			e.printStackTrace();
		}
		
        Integer account = 2;
        String user = "test";
        String password = "test";
        Integer id = 243;
        
        Transaction response = api.searchByAPIID(token, account, user, password, id);
        
        System.out.println(response.getTxid());
       
    }
    
    /**
     * Get transaction informations by file or string content
     *
     * Get transaction informations by file or string content 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    
    @Ignore
    @Test
    public void searchByContentTest() throws ApiException {
    	
    	String token = null;
		try {
			token = Token.sign("YOUR API PRIVATE KEY");
		} catch (Exception e) {
			e.printStackTrace();
		}
		
        Integer account = 1;
        String user = "test";
        String password = "test";
        String content = "test";
        
        List<Transaction> response = api.searchByContent(token, account, user, password, content);

        // TODO: test validations
    }
    
    /**
     * Get transaction informations by file or string hash
     *
     * Get transaction informations by file or string hash 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Ignore
    @Test
    public void searchByHashTest() throws ApiException {
        
    	String token = null;
		try {
			token = Token.sign("YOUR API PRIVATE KEY");
		} catch (Exception e) {
			e.printStackTrace();
		}
		
        Integer account = 1;
        String user = "test";
        String password = "test";
        String hash = "test";
        
        List<Transaction> response = api.searchByHash(token, account, user, password, hash);

        // TODO: test validations
    }
    
}
